
###REQUESTS FROM CLIENT APP


###GET req
get http://localhost:3000/user-api/users

###get a user by id
get http://localhost:3000/user-api/users/1

###POST req
post http://localhost:3000/user-api/user
Content-Type: application/json

{
    "id":3,
    "name":"vikas",
    "age":30
}



###PUT req
put http://localhost:3000/user-api/user
Content-Type: application/json

{
    "id":1,
    "name":"kiran kumar",
    "age":24
}



###DELETE req
delete http://localhost:3000/user-api/users/1



###PRODUCT reqs


get http://localhost:3000/product-api/products

###get a user by id
get http://localhost:3000/product-api/products/1